name: Dazhbog Docs CI

on:
  push:
    branches:
      - '**' # run on any branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    outputs:
      doc-artifact: ${{ steps.upload-docs.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build documentation
        run: cargo doc --no-deps --all-features

      # Upload docs as artifact to use later
      - name: Upload docs artifact
        id: upload-docs
        uses: actions/upload-artifact@v4
        with:
          name: rust-docs
          path: target/doc

  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-docs
          path: target/doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
